name: Deploy
on:
    push:
        branches:
            - main
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@master
              with:
                    host: 92.113.31.69
                    username: root
                    password: ${{ secrets.SSH_PASSWORD }}
                    script: |
                        cd /root/Ghabaty-Wildfire-Alert-App
                        git pull
                        docker compose up -d --build
                        